CREATE DATABASE SPMEDGROUP_APACHETWO;

USE SPMEDGROUP_APACHETWO;

CREATE TABLE CLINICA(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	HORARIO_FUNCIONAMENTO VARCHAR(255),
	CNPJ CHAR(14) NOT NULL UNIQUE,
	LOCALIDADE VARCHAR(255) NOT NULL
	RAZAO_SOCIAL VARCHAR(255) NOT NULL,
);

CREATE TABLE TIPO_USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) UNIQUE NOT NULL,
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	SENHA VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(50),
	ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA(ID)
	ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID),
);

CREATE TABLE ESPECIALIDADES(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE MEDICOS(
	ID INT IDENTITY PRIMARY KEY,
	ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID),
	CRM VARCHAR(255) NOT NULL UNIQUE
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID),
);

CREATE TABLE TIPO_STATUS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE PACIENTES(
	ID INT IDENTITY PRIMARY KEY,
	CPF CHAR(11) NOT NULL UNIQUE,
	DATA_NASCIMENTO DATETIME NOT NULL,
	RG CHAR(9) NOT NULL UNIQUE,
	ENDERECO VARCHAR(255) NOT NULL
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID),
);

CREATE TABLE CONSULTAS(
	ID INT IDENTITY PRIMARY KEY,
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTES(ID),
	ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID),
	DATA_CONSULTA DATETIME NOT NULL,
	ID_STATUS INT FOREIGN KEY REFERENCES TIPO_STATUS(ID) NOT NULL
);